hosts:
  - id: local
    label: Local
    type: local

projects:
  - name: Shell
    cwd: "~"
    command: $SHELL
    tmux: true
    agentType: shell
    tags:
      - local

  - name: Codex Workspace
    cwd: ~
    command: codex
    tmux: true
    agentType: codex
    tags:
      - agent
